#!/bin/bash

# pgbackup: backup databases to AWS s3
# Copyright (C) 2016 Mario Finelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get the local configuration
source ~/.pgbackup

if [[ -z ${PASSPHRASE+x} ]]; then
    echo >&2 "You must configure an encryption password!"
    exit 1
fi

if [[ ${#DBS[@]} -lt 1 ]]; then
    echo >&2 "You must specify at least one database to backup!"
    exit 1
fi

if [[ -z "$BACKUP_USER" ]]; then
    echo >&2 "You must specify a user to use for backups!"
    exit 1
fi

if [[ -z "$BUCKET" ]]; then
    echo >&2 "You must specify an s3 bucket for uploading!"
    exit 1
fi

command -v pg_dump >/dev/null 2>&1 || { \
    echo >&2 "Pg_dump does not seem to be available"; exit 1; \
}

command -v s3cmd >/dev/null 2>&1 || { \
    echo >&2 "S3cmd is not installed! Aborting!"; exit 1; \
}

# Make sure that s3cmd has been configured.
if [ ! -f ~/.s3cfg ]; then
    echo >&2 "S3cmd has not been configured yet. Aborting!"
    exit 2
fi
