#!/bin/bash

# pgbackup: backup databases to AWS s3
# Copyright (C) 2016 Mario Finelli
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get the local configuration
source ~/.pgbackup

if [[ -z ${PASSPHRASE+x} ]]; then
    echo >&2 "You must configure an encryption password!"
    exit 1
fi

if [[ ${#DBS[@]} -lt 1 ]]; then
    echo >&2 "You must specify at least one database to backup!"
    exit 1
fi

if [[ -z "$BUCKET" ]]; then
    echo >&2 "You must specify an s3 bucket for uploading!"
    exit 1
fi
